import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'

export default function about() {
    return (<>
        <Head>
            <title>Ducat India - Campus &amp; Industrial IT Training  School in Noida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1015237940"></script>
        </Head>
        <main>
            <>
                <Script
                    src="https://www.googletagmanager.com/gtag/js?id=AW-1015237940"
                    strategy="afterInteractive"
                />
                <Script id="google-analytics" strategy="afterInteractive">
                    {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    
                    gtag('config', 'AW-1015237940');

                    gtag('event', 'conversion', {'send_to': 'AW-1015237940/WVZyCOS6p7QBELSajeQD'});
                 `}
                </Script>
            </>
            <section className="m-auto p-5" style={{ width: "80%" }}>
                <div className="container thank-background">
                    <div className="card text-center" style={{ padding: "50px 100px" }}>
                        <h1 className="mb-4">Thank You</h1>
                        <h4 className="leading-normal">We got Your Enquiry!!!</h4>
                        <h5>Our Team Will Contact You Soon!!!</h5>
                        <Link href="/" className='btn search-background'>Go Back to Our Home Page</Link>
                    </div>
                </div>
            </section>
        </main>
    </>)
}
