import Head from 'next/head'


import Contact from "../components/posts/Contact"

export default function contcat() {
    return (<>
        <Head>
            <title>Ducat India - Campus &amp; Industrial IT Training  School in Noida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main> 
            <Contact/>
        </main>
    </>
    )
}
