import Head from 'next/head'
import Link from 'next/link'

export default function about() {
    return (<>
        <Head>
            <title>Ducat India - Campus &amp; Industrial IT Training  School in Noida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <section>
                <div className="bannerimg cover-image bg-background3" data-bs-image-src="../assets/images/banners/banner2.jpg">
                    <div className="header-text mb-0">
                        <div className="container">
                            <div className="text-center text-white ">
                                <h1 className="">Privacy Policy</h1>
                                <ol className="breadcrumb text-center">
                                    <li className="breadcrumb-item">
                                        <Link href="/">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active text-white" aria-current="page">About Us</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="sptb">
                <div className="container">
                    <div className="text-justify">
                        <h1 className="mb-4" style={{ borderLeft: "3px solid red" }}> Privacy Policy</h1>
                        <p className="leading-normal text-center">Training Industry, Inc. respects your privacy. Because we gather certain types of information about our users, we feel you should fully understand the terms and conditions surrounding the capture and use of that information. More information about how we use collected data is included in our Terms of Use.</p>
                    </div>
                </div>
            </section>
        </main>
    </>)
}
